package con;
/* loaded from: classes.dex */
public final class ZTTwt4eWi {
    public static final RxEtsNHUB CBQ5d1kRq;
    public static final RxEtsNHUB Dr7UqlxEV;
    public static final RxEtsNHUB EBQXiIPmm;
    public static final RxEtsNHUB GPLPRo6go;
    public static final RxEtsNHUB Ihm5o4uLx;
    public static final m0AevvDOv IzM1cD9ly;
    public static final RxEtsNHUB J4Ux7ym32;
    public static final RxEtsNHUB KlYagMRWx;
    public static final RxEtsNHUB L4EwGfXiQ;
    public static final m0AevvDOv MzoOEjc4X;
    public static final m0AevvDOv QSbMsHU5X;
    public static final m0AevvDOv RG6kpfv3v;
    public static final m0AevvDOv ShSN9wbzk;
    public static final m0AevvDOv XYT7vJqNO;
    public static final m0AevvDOv buPcffgdD;
    public static final long dXrmkklc8;
    public static final m0AevvDOv dfpT1j18n;
    public static final RxEtsNHUB i0Zug1mVk;
    public static final RxEtsNHUB iMyQMM6Qj;
    public static final m0AevvDOv igRQEZxnW;
    public static final m0AevvDOv iiGwOFFnr;
    public static final RxEtsNHUB ilHKhw3Yw;
    public static final RxEtsNHUB ixWaw2akD;
    public static final RxEtsNHUB kktL0P5MG;
    public static final m0AevvDOv ln3nf7LH3;
    public static final RxEtsNHUB n4UIOvAko;
    public static final RxEtsNHUB nlGCs0NZs;
    public static final m0AevvDOv qFBXIgpia;
    public static final m0AevvDOv vIbyhVf1d;
    public static final m0AevvDOv vNtjxmzUM;
    public static final m0AevvDOv vPSbyrYWX;
    public static final ZTTwt4eWi q3BipwRCk = new ZTTwt4eWi();
    public static final long tGV7Q6urW = BBVaGLNaU.ixWaw2akD(24.0d);
    public static final long dIocxURUo = BBVaGLNaU.sk5s77z6Q(16);
    public static final long kCA6Zs9sL = BBVaGLNaU.ixWaw2akD(0.5d);
    public static final long Puu3Rhg4F = BBVaGLNaU.ixWaw2akD(20.0d);
    public static final long yWvV4ePLl = BBVaGLNaU.sk5s77z6Q(14);
    public static final long oon79WMrY = BBVaGLNaU.ixWaw2akD(0.2d);
    public static final long kmSgne1rO = BBVaGLNaU.ixWaw2akD(16.0d);
    public static final long Bhmn1KIah = BBVaGLNaU.sk5s77z6Q(12);
    public static final long PSTqBLTET = BBVaGLNaU.ixWaw2akD(0.4d);
    public static final long qVUwofr5s = BBVaGLNaU.ixWaw2akD(64.0d);
    public static final long Eeka1udhb = BBVaGLNaU.sk5s77z6Q(57);
    public static final long sk5s77z6Q = BBVaGLNaU.ixWaw2akD(52.0d);
    public static final long WaUP0CF08 = BBVaGLNaU.sk5s77z6Q(45);
    public static final long i8XZMQc6Z = BBVaGLNaU.ixWaw2akD(0.0d);
    public static final long cAwN510t2 = BBVaGLNaU.ixWaw2akD(44.0d);
    public static final long IytU16YUK = BBVaGLNaU.sk5s77z6Q(36);
    public static final long CpG0imbht = BBVaGLNaU.ixWaw2akD(0.0d);
    public static final long AqaWJg0b4 = BBVaGLNaU.ixWaw2akD(40.0d);
    public static final long mUqPm6GBh = BBVaGLNaU.sk5s77z6Q(32);
    public static final long NyWTwPF6V = BBVaGLNaU.ixWaw2akD(0.0d);
    public static final long o4LF8RkoQ = BBVaGLNaU.ixWaw2akD(36.0d);
    public static final long V9LQMKGJe = BBVaGLNaU.sk5s77z6Q(28);
    public static final long QNqj6nIzv = BBVaGLNaU.ixWaw2akD(0.0d);
    public static final long TyB1UUd72 = BBVaGLNaU.ixWaw2akD(32.0d);
    public static final long juJ6pnCpu = BBVaGLNaU.sk5s77z6Q(24);
    public static final long j22ftfeNI = BBVaGLNaU.ixWaw2akD(0.0d);
    public static final long zHl31GGXU = BBVaGLNaU.ixWaw2akD(20.0d);
    public static final long ziwPzaoF3 = BBVaGLNaU.sk5s77z6Q(14);
    public static final long wIZEdYHUn = BBVaGLNaU.ixWaw2akD(0.1d);
    public static final long OpLJtmvFM = BBVaGLNaU.ixWaw2akD(16.0d);
    public static final long BL4OzhZBd = BBVaGLNaU.sk5s77z6Q(12);
    public static final long DuuXfa7LE = BBVaGLNaU.ixWaw2akD(0.5d);
    public static final long KBYw84i3W = BBVaGLNaU.ixWaw2akD(16.0d);
    public static final long INnK5Rew6 = BBVaGLNaU.sk5s77z6Q(11);
    public static final long SuKhTJIQc = BBVaGLNaU.ixWaw2akD(0.5d);
    public static final long M66hQ219i = BBVaGLNaU.ixWaw2akD(28.0d);
    public static final long R2hkbNqWf = BBVaGLNaU.sk5s77z6Q(22);
    public static final long IG30YE5GU = BBVaGLNaU.ixWaw2akD(0.0d);
    public static final long lqFHPHdW3 = BBVaGLNaU.ixWaw2akD(24.0d);
    public static final long oesmsHQJU = BBVaGLNaU.sk5s77z6Q(16);
    public static final long YmNRDyka4 = BBVaGLNaU.ixWaw2akD(0.2d);
    public static final long Ta2zrwkcM = BBVaGLNaU.ixWaw2akD(20.0d);
    public static final long uSBmk4hFZ = BBVaGLNaU.sk5s77z6Q(14);
    public static final long a8N8UmDyD = BBVaGLNaU.ixWaw2akD(0.1d);

    static {
        iErBJlccL ierbjlccl = iErBJlccL.q3BipwRCk;
        RxEtsNHUB rxEtsNHUB = Vyo35YgKP.J4Ux7ym32;
        J4Ux7ym32 = rxEtsNHUB;
        m0AevvDOv m0aevvdov = iErBJlccL.tGV7Q6urW;
        iiGwOFFnr = m0aevvdov;
        GPLPRo6go = rxEtsNHUB;
        vPSbyrYWX = m0aevvdov;
        CBQ5d1kRq = rxEtsNHUB;
        MzoOEjc4X = m0aevvdov;
        ilHKhw3Yw = rxEtsNHUB;
        long ixWaw2akD2 = BBVaGLNaU.ixWaw2akD(0.2d);
        BBVaGLNaU.kCA6Zs9sL(ixWaw2akD2);
        rstHZ5Gu8 rsthz5gu8 = QnjhYJNrZ.J4Ux7ym32;
        dXrmkklc8 = BBVaGLNaU.vNtjxmzUM(ixWaw2akD2 & 1095216660480L, -QnjhYJNrZ.tGV7Q6urW(ixWaw2akD2));
        RG6kpfv3v = m0aevvdov;
        ixWaw2akD = rxEtsNHUB;
        dfpT1j18n = m0aevvdov;
        iMyQMM6Qj = rxEtsNHUB;
        qFBXIgpia = m0aevvdov;
        nlGCs0NZs = rxEtsNHUB;
        vNtjxmzUM = m0aevvdov;
        i0Zug1mVk = rxEtsNHUB;
        igRQEZxnW = m0aevvdov;
        EBQXiIPmm = rxEtsNHUB;
        QSbMsHU5X = m0aevvdov;
        L4EwGfXiQ = rxEtsNHUB;
        m0AevvDOv m0aevvdov2 = iErBJlccL.J4Ux7ym32;
        IzM1cD9ly = m0aevvdov2;
        n4UIOvAko = rxEtsNHUB;
        XYT7vJqNO = m0aevvdov2;
        kktL0P5MG = rxEtsNHUB;
        ln3nf7LH3 = m0aevvdov2;
        Dr7UqlxEV = rxEtsNHUB;
        buPcffgdD = m0aevvdov;
        KlYagMRWx = rxEtsNHUB;
        ShSN9wbzk = m0aevvdov2;
        Ihm5o4uLx = rxEtsNHUB;
        vIbyhVf1d = m0aevvdov2;
    }
}
